spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect

  datasource:
    url: ${EXCDB}
    username: ${EXCNAME}
    password: ${EXCPASS}